name: Deploy to Snowflake

on:
  push:
    branches:
      - snowflake-dev
      - snowflake-prod

jobs:
  snowflake-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.4-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.4-linux_x86_64.bash

      - name: Fetch Git Repository in Snowflake
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_WAREHOUSE: COMPUTE_WH
        run: |
          ~/bin/snowsql -q 'ALTER GIT REPOSITORY "USER\$SAMUEL918".PUBLIC.snowf3_streamlit FETCH;'
          echo "✅ Snowflake Git Repository fetched successfully"
